Update JS with Add & Remove
ShaliniNayan/To-Do-List pull request #2
Opened 2023-05-04 15:45 UTC by ShaliniNayan

- Create a new JavaScript file for the new functionality.
- Implement a function for adding a new task (add a new element to the array).
- Implement a function for deleting a task (remove an element from the array).
- Implement a function for editing task descriptions.
- By default new tasks should have the property completed set to false and the property index set to the value of the new array length
- Deleting a task should update all remaining items' indexes, so they represent the current list order and are unique.
- All changes to the To Do List should be saved in local storage.

2023-05-04 19:02 UTC, Ismailco requested changes
### Hi @ShaliniNayan, 

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ No linter errors
✔️ Used GitHub Flow
✔️ Work documented professionally

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-04 19:11 UTC, ShaliniNayan commented on src/index.js
> +// Select the Elements
Thanks & Noted

2023-05-04 19:11 UTC, ShaliniNayan commented on src/index.js
> +function addToDo(toDo, id, done, trash) {
Thanks & Noted.

2023-05-04 19:11 UTC, ShaliniNayan commented on src/index.js
> +function loadList(listArray) {
Thanks & Noted.

2023-05-04 21:16 UTC, ShaliniNayan commented on src/index.js
> +function removeToDo(element) {
Sorry to differ but totally working on my computer.

2023-05-04 21:16 UTC, ShaliniNayan commented on src/index.js
> +function removeToDo(element) {
Thanks & Noted.

2023-05-04 22:34 UTC, rloterh reviewed
Hi Shalini, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Your app cannot run correctly as the supposed index.js file is missing from the project directory. Kindly ensure to include this file and that app runs correctly.

**Kindly remove/update all similar to the underlined:**
![image](https://user-images.githubusercontent.com/12745474/236343470-a4e77587-ba03-477a-828e-e67cd852417c.png)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-05 08:51 UTC, Ismailco approved these changes
### Hi @ShaliniNayan, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


## Highlights

✔️ Nice UI
✔️ No linter errors
✔️ Used GitHub Flow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 08:52 UTC, merged